const fonts = {
  bold: 'SFPRODISPLAYBOLD',
  regular: 'SFPRODISPLAYREGULAR',
  medium: 'SFPRODISPLAYMEDIUM',
  semibold: 'SFPRODISPLAYMEDIUM',
  light: 'SFPRODISPLAYREGULAR',
};
const images = {
  logo: require('../../assets/logo.png'),
  auth1: require('../../assets/auth1.png'),
  googleIcon: require('../../assets/googleIcon.png'),
  more: require('../../assets/more.png'),
};
const colors = {
  grey: '#868889',
  green: 'green',
  primaryColor: '#AEDC81',
};
const products = [
  {
    id: 1,
    name: 'Fresh Peach',
    price: 8,
    quantity: 'dozen',
    image: require('../../assets/peach-24.png'),
    new: '1',
    islike: '0',
    isDiscount: '1',
    dicountp: '16',
    category: 'Fruits',
    feature: '1',
    rating: 4.8,
    description:
      'Enjoy the rich sweetness of handpicked fresh peaches. Perfect for snacks, desserts, and smoothies. Juicy and full of flavor in every bite.',
  },
  {
    id: 2,
    name: 'Avocado',
    price: 7,
    quantity: '1kg',
    image: require('../../assets/aocado-2.png'),
    new: '0',
    islike: '0',
    isDiscount: '0',
    dicountp: '16',
    category: 'Fruits',
    feature: '0',
    rating: 4.5,
    description:
      'Creamy and nutritious avocados packed with healthy fats. Great for salads, toast, or making delicious guacamole. A must-have superfood.',
  },
  {
    id: 3,
    name: 'Pineapple',
    price: 9.9,
    quantity: '1/2kg',
    image: require('../../assets/pineapple-pieces.png'),
    new: '1',
    islike: '0',
    isDiscount: '0',
    dicountp: '16',
    category: 'Fruits',
    feature: '1',
    rating: 4.2,
    description:
      'Freshly sliced pineapple pieces, sweet and tangy. Perfect for fruit salads or juicing. Naturally refreshing and rich in Vitamin C.',
  },
  {
    id: 4,
    name: 'Black Grapes',
    price: 7.05,
    quantity: '2kg',
    image: require('../../assets/grapes-31.png'),
    new: '0',
    islike: '1',
    isDiscount: '1',
    dicountp: '30',
    category: 'Fruits',
    feature: '0',
    rating: 4.7,
    description:
      'Juicy and sweet black grapes with a rich flavor. Packed with antioxidants and perfect for healthy snacking. Enjoy them fresh or chilled.',
  },
  {
    id: 5,
    name: 'Pomegranate',
    price: 2.09,
    quantity: '1/2kg',
    image: require('../../assets/pomegranate-11.png'),
    new: '0',
    islike: '0',
    isDiscount: '0',
    dicountp: '16',
    category: 'Fruits',
    feature: '1',
    rating: 4.3,
    description:
      'Bright red pomegranate seeds bursting with juicy goodness. Known for their antioxidants and health benefits. Great in salads or eaten raw.',
  },
  {
    id: 6,
    name: 'Fresh Broccoli',
    price: 3,
    quantity: '1kg',
    image: require('../../assets/green-fresh-broccoli.png'),
    new: '1',
    islike: '1',
    isDiscount: '0',
    dicountp: '16',
    category: 'Vegetables',
    feature: '1',
    rating: 4.6,
    description:
      'Crisp and nutrient-rich fresh broccoli. Ideal for steaming, stir-frying, or roasting. A healthy choice for every meal.',
  },
  {
    id: 7,
    name: 'Carrots',
    price: 2.5,
    quantity: '1kg',
    image: require('../../assets/carrots.png'),
    new: '0',
    islike: '0',
    isDiscount: '1',
    dicountp: '10',
    category: 'Vegetables',
    feature: '1',
    rating: 4.1,
    description:
      'Crunchy and sweet carrots loaded with Vitamin A. Great raw, boiled, or roasted. A healthy snack or side for your meals.',
  },
  {
    id: 8,
    name: 'Tomatoes',
    price: 1.8,
    quantity: '1kg',
    image: require('../../assets/tomatoes.png'),
    new: '1',
    islike: '0',
    isDiscount: '0',
    dicountp: '5',
    category: 'Vegetables',
    feature: '0',
    rating: 3.9,
    description:
      'Juicy red tomatoes full of flavor. Perfect for sauces, curries, and salads. Freshly harvested and pesticide-free.',
  },
  {
    id: 9,
    name: 'Coca Cola',
    price: 1.2,
    quantity: '500ml',
    image: require('../../assets/cocacola.png'),
    new: '1',
    islike: '0',
    isDiscount: '1',
    dicountp: '20',
    category: 'Beverages',
    feature: '0',
    rating: 4.5,
    description:
      'Classic Coca Cola with its iconic taste and fizz. Refreshing and energizing, best served chilled. A perfect companion for any meal.',
  },
  {
    id: 10,
    name: 'Pepsi',
    price: 1.1,
    quantity: '500ml',
    image: require('../../assets/pepsi.png'),
    new: '0',
    islike: '1',
    isDiscount: '0',
    dicountp: '0',
    category: 'Beverages',
    feature: '1',
    rating: 4.4,
    description:
      'Bold and bubbly Pepsi for a quick refresh. Great with snacks or on its own. Crisp, cool, and always satisfying.',
  },
  {
    id: 11,
    name: 'Basmati Rice',
    price: 12,
    quantity: '5kg',
    image: require('../../assets/rice.png'),
    new: '0',
    islike: '0',
    isDiscount: '1',
    dicountp: '15',
    category: 'Grocery',
    feature: '0',
    rating: 4.6,
    description:
      'Aromatic long-grain Basmati rice. Ideal for biryani, pilaf, or everyday meals. Cooks fluffy with a rich fragrance.',
  },
  {
    id: 12,
    name: 'Wheat Flour',
    price: 6,
    quantity: '5kg',
    image: require('../../assets/flour.png'),
    new: '1',
    islike: '1',
    isDiscount: '0',
    dicountp: '0',
    category: 'Grocery',
    feature: '1',
    rating: 4.2,
    description:
      'Premium wheat flour for soft, fluffy chapatis and breads. Stone-ground and fresh. Perfect for daily home cooking.',
  },
  {
    id: 13,
    name: 'Sunflower Oil',
    price: 10,
    quantity: '2L',
    image: require('../../assets/sunflower-oil.png'),
    new: '0',
    islike: '0',
    isDiscount: '1',
    dicountp: '25',
    category: 'Edible oil',
    feature: '0',
    rating: 4.4,
    description:
      'Light and healthy sunflower oil, perfect for frying and cooking. Rich in Vitamin E and cholesterol-free.',
  },
  {
    id: 14,
    name: 'Canola Oil',
    price: 9.5,
    quantity: '2L',
    image: require('../../assets/canola-oil.png'),
    new: '1',
    islike: '0',
    isDiscount: '0',
    dicountp: '0',
    category: 'Edible oil',
    feature: '1',
    rating: 4.0,
    description:
      'Heart-smart canola oil with a neutral flavor. Ideal for baking and sautéing. Low in saturated fat.',
  },
  {
    id: 15,
    name: 'Laundry Detergent',
    price: 5.5,
    quantity: '1kg',
    image: require('../../assets/detergent.png'),
    new: '0',
    islike: '1',
    isDiscount: '1',
    dicountp: '10',
    category: 'Household',
    feature: '0',
    rating: 3.8,
    description:
      'Powerful laundry detergent for bright, clean clothes. Removes tough stains while being gentle on fabric.',
  },
  {
    id: 16,
    name: 'Toilet Paper',
    price: 3,
    quantity: '6 rolls',
    image: require('../../assets/toilet-paper.png'),
    new: '1',
    islike: '0',
    isDiscount: '0',
    feature: '1',
    dicountp: '0',
    category: 'Household',
    rating: 4.1,
    description:
      'Soft and absorbent toilet paper. Gentle on skin and strong enough for daily use. Comes in a value pack.',
  },
  {
    id: 17,
    name: 'Baby Shampoo',
    price: 4.5,
    quantity: '250ml',
    image: require('../../assets/baby-shampoo.png'),
    new: '1',
    islike: '1',
    isDiscount: '1',
    feature: '0',
    dicountp: '18',
    category: 'Babycare',
    rating: 4.7,
    description:
      'Tear-free baby shampoo with a gentle formula. Leaves hair soft and clean with a mild, pleasant scent.',
  },
  {
    id: 18,
    name: 'Baby Diapers',
    price: 15,
    feature: '1',
    quantity: 'Pack of 20',
    image: require('../../assets/diapers.png'),
    new: '0',
    islike: '1',
    isDiscount: '1',
    dicountp: '12',
    category: 'Babycare',
    rating: 4.5,
    description:
      'Soft, breathable diapers with excellent absorption. Keeps your baby dry and comfortable throughout the day.',
  },
  {
    id: 19,
    name: 'Onion',
    price: 5,
    quantity: '1kg',
    image: require('../../assets/onion.png'),
    new: '1',
    islike: '1',
    isDiscount: '0',
    dicountp: '16',
    category: 'Vegetables',
    feature: '0',
    rating: 4.0,
    description:
      'Versatile and flavorful onions essential in every kitchen. Adds depth and aroma to a variety of dishes. Fresh and long-lasting.',
  },
];
export { fonts, images, colors, products };
