import { NavigatorScreenParams } from '@react-navigation/native';
export type RootTabParamList = {
  Home: undefined;
  Favourite: undefined;
  // Cart: undefined;
  Profile: undefined;
};
export type RootStackParamList = {
  Welcome: undefined;
  CreateAccount: undefined;
  Login: undefined;
  Forgot: undefined;
  VerifyNumber: undefined;
  Cart: undefined;
  ConfirmCode: undefined;
  ConfirmCodeForgot: undefined;
  BottomNav: NavigatorScreenParams<RootTabParamList>;
  ProductDetail: undefined;
  Categories: undefined;
  CategoryProducts: undefined;
  About: undefined;
  MyOrders: undefined;
  Address: undefined;
  Home: undefined;
  AddAddress: undefined;
  CreditCards: undefined;
  AddCard: undefined;
  Transactions: undefined;
  Notifications: undefined;
  CreateAccountRider: undefined;
  LoginRider: undefined;
  VerifyNumberRider: undefined;
  ConfirmCodeRider: undefined;
  HomeRider: undefined;
  MapRider: undefined;
  ProfileRider: undefined;
  ForgotRider: undefined;
  ConfirmCodeForgotRider: undefined;
  ChangePassword: undefined;
  ChangePasswordRider: undefined;
};
